import { Injectable } from '@angular/core';
import { Profesor } from '../interfaces/profesor.interface';

@Injectable({
  providedIn: 'root'
})
export class DataProvidersService {

  constructor() { }
  
  profesores: Profesor[] = [
    {nombre:'Carlos Loria'},
    {nombre:'Maikol Guzman'},
    {nombre:'Olger Calderon'},
    {nombre:'Sandra Cabrera'},
    {nombre:'Erick Lopez'},
    {nombre:'Miguel Corrales'},
    {nombre:'Oldemar Rodríguez'},
    {nombre:'Oscar Reyes'},
    {nombre:'Majid Bayani'},
    {nombre:'José Vindas'},
    {nombre:'José Sánchez'},
    {nombre:'José Calvo'},
    {nombre:'Georges Alfaro'},
    {nombre:'Daniel Vargas'},
    {nombre:'Marianela Solano'},
    {nombre:'Hellen Bolaños'},
    {nombre:'Gregorio Villalobos'},
    {nombre:'Santiago Camaño'},
    {nombre:'Henry Guevara'},
    {nombre:'Cesar Valverde'},
    {nombre:'Marilyn Peraza'},
    {nombre:'Carolina Gomez'},
  ]
  
  NRCs: string[] = [
    '40090',
    '40080',
    '40060',
    '40070',
    '40072',
    '40078',
    '40050',
    '40083',
    '90028',
    '50815',
    '41749',
    '50079',
    '50084',
    '50085',
    '50088',
    '50089',
    '50221',
    '50222',
    '50223',
    '50225',
    '50226',
    '50138',
    '50140',
    '50141',
    '50142',
    '50143',
    '50144',
    '50230',
    '50231',
    '50232',
    '50233',
  ]
  
  codigosDeCursos: string[] = [
    'EIF200',
    'MAT030',
    'LIX-410',
    'EIF201',
    'MAT002',
    'LIX-411',
    'EIF204',
    'MAT005',
    'EIF202',
    'EIF203',
    'LIX-412',
    'EIF206',
    'EIF207',
    'EIF205',
    'EIF404',
    'MAT006',
    'EIF209',
    'EIF210',
    'EIF211',
    'EIF212',
    'EIF208',
    'EIF400',
    'EIF401',
    'EIF402',
    'EIF412',
    'EIF407',
    'EIF411',
    'EIF406',
    'EIF413',
    'EIF408',
    'EIF409',
    'EIF410',
  ]

  nombreDeCursos: string[] = [
    'Fundamentos de Informática',
    'Matemática para Informática',
    'Cálculo I',
    'Algebra Lineal',
    'Soporte Técnico',
    'Estructura Discretas Para Informática',
    'Estructuras De Datos',
    'Arquitectura De Computadoraes',
    'La Organización y Su Entorno',
    'Probabilidad y Estadística Para Informática',
    'Diseño e Implementación de Bases de Datos',
    'Sistemas Operativos',
    'Comunicación y Redes de Computadoras',
    'Paradigmas de Programación',
    'Administración de Bases de Datos',
    'Investigación de Operaciones y sus Aplicaciones',
    'Liderazgo y Organización',
    'Diseño y Programación de Plataformas Móviles',
    'Métodos de Investigación Científica en Informática',
    'Proyecto y su Aplicación en la Organización (PPS)',
    'Aplicaciones Informática Globales',
    'Informática y Sociedad',
    'Inglés Integrado I',
    'Inglés Integrado II',
    'Inglés Integrado III',
    'Programación I',
    'Programación II',
    'Programación III',
    'Programación IV',
    'Ingeniería de Sistemas I',
    'Ingeniería de Sistemas II',
    'Ingeniería de Sistemas III',
  ]

}
